/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author Dana Chavez
 */
public class Identificacion extends javax.swing.JPanel {
    
    VentanaRegistro ventanaPrincipal;
    FontManager fontManager = new FontManager();
    
    public Identificacion(VentanaRegistro ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setBackground(new java.awt.Color(7, 76, 64));
        jTextFieldUsuario.setFont(fontManager.getAfacadRegular(20f));
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setText("   Usuario");
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 248, 49));

        jLabelTitulo.setFont(fontManager.getAfacadBold(42f));
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Identificate");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 30, 210, 65));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAgregarImagen.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabelRegistro.setFont(fontManager.getAfacadMedium(16f));
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setText("Elige un nombre de usuario.");
        add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 250, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonFinalizar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
