/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import tune.sistemabibliotecadominio.dtos.NuevoUsuarioDTO;
import tune.sistemabibliotecanegocio.exception.NegocioException;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;
import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author Dana Chavez
 */
public class Identificacion extends javax.swing.JPanel {

    VentanaRegistro ventanaPrincipal;
    FontManager fontManager = new FontManager();
    NuevoUsuarioDTO nuevoUsuario;
    ControlNavegacion control;

    public Identificacion(ControlNavegacion control, VentanaRegistro ventanaPrincipal, NuevoUsuarioDTO nuevoUsuario) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        this.nuevoUsuario = nuevoUsuario;
        this.control = control;
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonImagenPerfil = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setBackground(new java.awt.Color(7, 76, 64));
        jTextFieldUsuario.setFont(fontManager.getAfacadRegular(20f));
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setText("   Usuario");
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 248, 49));

        jLabelTitulo.setFont(fontManager.getAfacadBold(42f));
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Identificate");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 30, 210, 65));

        jButtonImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAgregarImagen.png"))); // NOI18N
        jButtonImagenPerfil.setBorder(null);
        jButtonImagenPerfil.setContentAreaFilled(false);
        jButtonImagenPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonImagenPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagenPerfilActionPerformed(evt);
            }
        });
        add(jButtonImagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabelRegistro.setFont(fontManager.getAfacadMedium(16f));
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setText("Elige un nombre de usuario.");
        add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 250, -1));

        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonFinalizar.png"))); // NOI18N
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImagenPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagenPerfilActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg", "gif"));
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            nuevoUsuario.setImagenPerfil(selectedFile.getAbsolutePath());

            ImageIcon originalIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image scaledImage = originalIcon.getImage().getScaledInstance(
                    jButtonImagenPerfil.getWidth(),
                    jButtonImagenPerfil.getHeight(),
                    Image.SCALE_SMOOTH
            );
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            jButtonImagenPerfil.setIcon(scaledIcon);

            JOptionPane.showMessageDialog(this, "Imagen de perfil cargada correctamente.");
        }
    }//GEN-LAST:event_jButtonImagenPerfilActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        nuevoUsuario.setNombreusuario(jTextFieldUsuario.getText());
        try {
            control.registrarUsuario(nuevoUsuario);
        } catch (NegocioException ex) {
            Logger.getLogger(Identificacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImagenPerfil;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
