/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import tune.sistemabibliotecapresentacion.control.ControlNavegacion;
import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author leoca
 */
public class PanelPerfilUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelPerfilUsuario
     */
    FontManager fontManager = new FontManager();
    ControlNavegacion control;
    VentanaPrincipal ventanaPrincipal;
    
    public PanelPerfilUsuario(ControlNavegacion control, VentanaPrincipal ventanaPrincipal) {
        this.control = control;
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        jLabelNombreUsuario.setFont(fontManager.getAfacadBold(96));
        jButtonEditarPerfil.setFont(fontManager.getAfacadMedium(20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenPerfil = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jButtonEditarPerfil = new javax.swing.JButton();
        jButtonGeneros = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 33, 27));
        setMinimumSize(new java.awt.Dimension(1020, 763));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NoImagenPerfil.png"))); // NOI18N
        add(jLabelImagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 180));

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 96)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUsuario.setText("Usuario");
        add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 730, 90));

        jButtonEditarPerfil.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonEditarPerfil.setForeground(new java.awt.Color(153, 173, 170));
        jButtonEditarPerfil.setText("Editar perfil");
        jButtonEditarPerfil.setBorderPainted(false);
        jButtonEditarPerfil.setContentAreaFilled(false);
        jButtonEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, 30));

        jButtonGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonGenerosExcluidos.png"))); // NOI18N
        jButtonGeneros.setBorderPainted(false);
        jButtonGeneros.setContentAreaFilled(false);
        jButtonGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degradado.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarPerfil;
    private javax.swing.JButton jButtonGeneros;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagenPerfil;
    private javax.swing.JLabel jLabelNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
