/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import tune.sistemabibliotecadominio.dtos.AlbumDTO;
import tune.sistemabibliotecanegocio.exception.NegocioException;
import tune.sistemabibliotecanegocio.implementaciones.AlbumesBO;
import tune.sistemabibliotecanegocio.interfaces.IAlbumesBO;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;

/**
 *
 * @author leoca
 */
public class PanelAñadirAlbum extends javax.swing.JPanel {

    /**
     * Creates new form PanelAñadirAlbum
     */
    IAlbumesBO albumesBO;
    ControlNavegacion control;
    String artistaId;
    
    public PanelAñadirAlbum(IAlbumesBO albumesBO, ControlNavegacion control,String artistaId) {
        initComponents();
        this.albumesBO = albumesBO;
        this.control = control;
        this.artistaId = artistaId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuardar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldURL = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonGuardar.png"))); // NOI18N
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setContentAreaFilled(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 530, 40));
        add(jTextFieldGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 530, 40));
        add(jTextFieldURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 530, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAñadirAlbum.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        String nombre = jTextFieldNombre.getText().trim();
        String genero = jTextFieldGenero.getText().trim();
        String url = jTextFieldURL.getText().trim();

        if (nombre.isEmpty() || genero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete nombre y genero.");
            return;
        }

        AlbumDTO albumNuevo = new AlbumDTO();
        albumNuevo.setNombre(nombre);
        albumNuevo.setGeneroMusical(genero);
        albumNuevo.setImagenPortada(url);

        try {
            albumesBO.registrarAlbum(albumNuevo, artistaId);
            JOptionPane.showMessageDialog(this, "Artista guardado con éxito.");
            control.actualizarPaneles();
            SwingUtilities.getWindowAncestor(this).dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
