/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import tune.sistemabibliotecadominio.dtos.ArtistaDTO;
import tune.sistemabibliotecanegocio.exception.NegocioException;
import tune.sistemabibliotecanegocio.interfaces.IArtistasBO;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;

/**
 *
 * @author leoca
 */
public class PanelAñadirArtista extends javax.swing.JPanel {

    /**
     * Creates new form PanelAñadirArtista
     */
    IArtistasBO artistasBO;
    ControlNavegacion control;

    public PanelAñadirArtista(IArtistasBO artistasBO, ControlNavegacion control) {
        this.artistasBO = artistasBO;
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldURL = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldURL.setBackground(new java.awt.Color(66, 73, 64));
        jTextFieldURL.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 520, 40));

        jTextFieldNombre.setBackground(new java.awt.Color(66, 73, 64));
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 520, 40));

        jTextFieldGenero.setBackground(new java.awt.Color(66, 73, 64));
        jTextFieldGenero.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 520, 40));

        jComboBoxTipo.setBackground(new java.awt.Color(66, 73, 64));
        jComboBoxTipo.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solista", "Banda" }));
        add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 202, 520, 40));

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonGuardar.png"))); // NOI18N
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setContentAreaFilled(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAñadirArtista.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        String nombre = jTextFieldNombre.getText().trim();
        String genero = jTextFieldGenero.getText().trim();
        String url = jTextFieldURL.getText().trim();
        String tipoSeleccionado = (String) jComboBoxTipo.getSelectedItem();

        if (nombre.isEmpty() || genero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete nombre y genero.");
            return;
        }

        ArtistaDTO artistaNuevo = new ArtistaDTO();
        artistaNuevo.setNombre(nombre);
        artistaNuevo.setTipo(tipoSeleccionado);
        artistaNuevo.setGeneroMusical(genero);
        artistaNuevo.setImagen(url);

        try {
            artistasBO.guardarArtista(artistaNuevo);
            JOptionPane.showMessageDialog(this, "Artista guardado con éxito.");
            control.actualizarPaneles();
            SwingUtilities.getWindowAncestor(this).dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
}
