/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import tune.sistemabibliotecadominio.entidades.Usuario;
import tune.sistemabibliotecanegocio.interfaces.IUsuariosBO;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;

/**
 *
 * @author leoca
 */
public class PanelIngresarNuevaContraseña extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarNuevaContraseña
     */
    ControlNavegacion control;
    VentanaPrincipal ventanaPrincipal;
    IUsuariosBO usuariosBO;
    PanelEditarUsuario panelEditarUsuario;

    public PanelIngresarNuevaContraseña(ControlNavegacion control, VentanaPrincipal ventanaPrincipal, IUsuariosBO usuariosBO, PanelEditarUsuario panelEditarUsuario) {
        this.control = control;
        this.ventanaPrincipal = ventanaPrincipal;
        this.usuariosBO = usuariosBO;
        this.panelEditarUsuario = panelEditarUsuario;
        initComponents();
        jButtonGuardarContraseña.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTextoIngresar = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonContinuar = new javax.swing.JButton();
        jButtonGuardarContraseña = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NoImagenPerfil.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabelTextoIngresar.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabelTextoIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoIngresar.setText("Ingrese contraseña actual");
        add(jLabelTextoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 500, 60));

        jPasswordField.setBackground(new java.awt.Color(66, 73, 64));
        add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 450, 50));

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonContinuarContraseña.png"))); // NOI18N
        jButtonContinuar.setBorderPainted(false);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        add(jButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, 70));

        jButtonGuardarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonGuardar.png"))); // NOI18N
        jButtonGuardarContraseña.setBorderPainted(false);
        jButtonGuardarContraseña.setContentAreaFilled(false);
        jButtonGuardarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarContraseñaActionPerformed(evt);
            }
        });
        add(jButtonGuardarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, 70));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVerdeContraseña.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        try {
            boolean esCorrecta = usuariosBO.verificarContraseñaActual(jPasswordField.getText());
            if (esCorrecta) {
                javax.swing.JOptionPane.showMessageDialog(this, "Contraseña verificada. Ahora puedes ingresar una nueva.");

                jLabelTextoIngresar.setText("Ingrese contraseña nueva");
                jPasswordField.setText("");
                jButtonContinuar.setVisible(false);
                jButtonGuardarContraseña.setVisible(true);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonGuardarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarContraseñaActionPerformed
        String nueva = jPasswordField.getText().trim();
        if (nueva.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        panelEditarUsuario.setContraseñaNueva(nueva);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButtonGuardarContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonGuardarContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTextoIngresar;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
}
