/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import tune.sistemabibliotecadominio.entidades.Usuario;
import tune.sistemabibliotecanegocio.exception.NegocioException;
import tune.sistemabibliotecanegocio.interfaces.IUsuariosBO;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;
import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author leoca
 */
public class PanelPerfilUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelPerfilUsuario
     */
    FontManager fontManager = new FontManager();
    ControlNavegacion control;
    VentanaPrincipal ventanaPrincipal;
    Usuario usuarioActual;
    IUsuariosBO usuariosBO;

    public PanelPerfilUsuario(ControlNavegacion control, VentanaPrincipal ventanaPrincipal, IUsuariosBO usuariosBO) throws NegocioException {
        initComponents();
        this.control = control;
        this.ventanaPrincipal = ventanaPrincipal;
        this.usuariosBO = usuariosBO;
        this.usuarioActual = control.obtenerUsuarioActual();
        jLabelNombreUsuario.setFont(fontManager.getAfacadBold(96));
        jButtonEditarPerfil.setFont(fontManager.getAfacadMedium(20));
        jLabelPerfilTexto.setFont(fontManager.getAfacadMedium(20));
        establecerDatos();
    }

    public void establecerDatos() {
        jLabelNombreUsuario.setText(usuarioActual.getNombreusuario());
        String rutaImagen = usuarioActual.getImagenPerfil();
        if (rutaImagen != null && !rutaImagen.isEmpty()) {
            ImageIcon originalIcon = new ImageIcon(rutaImagen);
            if (originalIcon.getIconWidth() > 0 && originalIcon.getIconHeight() > 0) {
                Image imagenEscalada = originalIcon.getImage().getScaledInstance(
                        200,
                        200,
                        Image.SCALE_SMOOTH
                );
                jLabelImagenPerfil.setIcon(new ImageIcon(imagenEscalada));
            } else {
                jLabelImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NoImagenPerfil.png")));
            }
        } else {
            jLabelImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NoImagenPerfil.png")));
        }
    }

    public void mostrarPanelEditarUsuarioFlotante() {
        try {
            JPanel fondoOscuro = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    g.setColor(new Color(0, 0, 0, 150));
                    g.fillRect(0, 0, getWidth(), getHeight());
                    super.paintComponent(g);
                }
            };
            fondoOscuro.setOpaque(false);
            fondoOscuro.setLayout(new GridBagLayout());

            PanelEditarUsuario panelEditar = new PanelEditarUsuario(usuarioActual, control, ventanaPrincipal, usuariosBO, this);
            panelEditar.setOpaque(true);
            panelEditar.setPreferredSize(new Dimension(850, 500));
            fondoOscuro.add(panelEditar);

            JDialog dialogo = new JDialog((Frame) null, Dialog.ModalityType.APPLICATION_MODAL);
            dialogo.setUndecorated(true);
            dialogo.setBackground(new Color(0, 0, 0, 0));
            dialogo.setContentPane(fondoOscuro);
            dialogo.setSize(1138, 868);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (screenSize.width - dialogo.getWidth()) / 2;
            int y = (screenSize.height - dialogo.getHeight()) / 2 - 9;
            dialogo.setLocation(x, y);

            dialogo.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void actualizarDatos(){
        usuarioActual=usuariosBO.obtenerUsuarioActual();
        establecerDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagenPerfil = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jButtonEditarPerfil = new javax.swing.JButton();
        jButtonGeneros = new javax.swing.JButton();
        jLabelPerfilTexto = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 33, 27));
        setMinimumSize(new java.awt.Dimension(1020, 763));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NoImagenPerfil.png"))); // NOI18N
        add(jLabelImagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 180));

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 96)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUsuario.setText("Usuario");
        add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 730, 90));

        jButtonEditarPerfil.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButtonEditarPerfil.setForeground(new java.awt.Color(153, 173, 170));
        jButtonEditarPerfil.setText("Editar perfil");
        jButtonEditarPerfil.setBorderPainted(false);
        jButtonEditarPerfil.setContentAreaFilled(false);
        jButtonEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarPerfilActionPerformed(evt);
            }
        });
        add(jButtonEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, 30));

        jButtonGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonGenerosExcluidos.png"))); // NOI18N
        jButtonGeneros.setBorderPainted(false);
        jButtonGeneros.setContentAreaFilled(false);
        jButtonGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jLabelPerfilTexto.setForeground(new java.awt.Color(153, 173, 170));
        jLabelPerfilTexto.setText("Perfil");
        add(jLabelPerfilTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degradado.png"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarPerfilActionPerformed
        mostrarPanelEditarUsuarioFlotante();
    }//GEN-LAST:event_jButtonEditarPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarPerfil;
    private javax.swing.JButton jButtonGeneros;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagenPerfil;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelPerfilTexto;
    // End of variables declaration//GEN-END:variables
}
