/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import tune.sistemabibliotecadominio.entidades.dtos.NuevoUsuarioDTO;
import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author Dana Chavez
 */
public class Registro extends javax.swing.JPanel {
    
    FontManager fontManager = new FontManager();
    VentanaRegistro ventanaPrincipal;
    
    public Registro(VentanaRegistro ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonContinuar = new javax.swing.JButton();
        jLabelInicio = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(fontManager.getAfacadBold(52f));
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Registrate en Tune");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 390, 65));

        jTextFieldCorreo.setBackground(new java.awt.Color(7, 76, 64));
        jTextFieldCorreo.setFont(fontManager.getAfacadRegular(20f));
        jTextFieldCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCorreo.setText("   E-mail");
        jTextFieldCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 248, 49));

        jPassword.setBackground(new java.awt.Color(7, 76, 64));
        jPassword.setFont(fontManager.getAfacadRegular(20f));
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.setText("Contrasena");
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 248, 49));

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonContinuar.png"))); // NOI18N
        jButtonContinuar.setBorder(null);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        add(jButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jLabelInicio.setFont(fontManager.getAfacadMedium(15f));
        jLabelInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInicio.setText("Ya tienes una cuenta?");
        add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        jButtonInicio.setFont(fontManager.getAfacadMedium(15f));
        jButtonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setText("Inicia sesion.");
        jButtonInicio.setBorder(null);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMusica.png"))); // NOI18N
        add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 6, 240, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        ventanaPrincipal.mostrarInicioSesion();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        NuevoUsuarioDTO usuario = new NuevoUsuarioDTO();
        usuario.setCorreo(jTextFieldCorreo.getText());
        usuario.setContrasena(jPassword.getText());
        
        ventanaPrincipal.mostrarIdentificacion(usuario);
    }//GEN-LAST:event_jButtonContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldCorreo;
    // End of variables declaration//GEN-END:variables
}
