/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import java.awt.CardLayout;
import tune.sistemabibliotecadominio.dtos.NuevoUsuarioDTO;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;

/**
 *
 * @author Dana Chavez
 */
public class VentanaRegistro extends javax.swing.JFrame {
    
    ControlNavegacion control;
    NuevoUsuarioDTO usuario = new NuevoUsuarioDTO();
    
    public VentanaRegistro(ControlNavegacion control) {
        initComponents();
        this.control = control;
        setLocationRelativeTo(null);
        
        jPanelForms.setLayout(new CardLayout());
        mostrarInicioSesion();
    }
    
    public void mostrarInicioSesion() {
        InicioSesion panelInicio = new InicioSesion(control, this);
        jPanelForms.add(panelInicio, "inicio");
        CardLayout cl = (CardLayout) jPanelForms.getLayout();
        cl.show(jPanelForms, "inicio");
    }
    
    public void mostrarRegistro(){
        Registro panelRegistro = new Registro(this);
        jPanelForms.add(panelRegistro, "registro");
        CardLayout cl = (CardLayout) jPanelForms.getLayout();
        cl.show(jPanelForms, "registro");
    }
    
    public void mostrarIdentificacion(NuevoUsuarioDTO nuevoUsuarioDTO){
        this.usuario = nuevoUsuarioDTO;
        Identificacion panelIdentificacion = new Identificacion(control, this, usuario);
        jPanelForms.add(panelIdentificacion, "identificacion");
        CardLayout cl = (CardLayout) jPanelForms.getLayout();
        cl.show(jPanelForms, "identificacion");
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    public NuevoUsuarioDTO getUsuario() {
        return usuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelForms = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelForms.setOpaque(false);
        jPanelForms.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanelForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 580, 570));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoInicioSesion.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanelForms;
    // End of variables declaration//GEN-END:variables
}
