/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tune.sistemabibliotecapresentacion;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tune.sistemabibliotecanegocio.exception.NegocioException;
import tune.sistemabibliotecanegocio.interfaces.IInsercionMasivaBO;
import tune.sistemabibliotecapresentacion.control.ControlNavegacion;

/**
 *
 * @author Dana Chavez
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private IInsercionMasivaBO insercionMasivaBO;
    private static final Logger LOG = Logger.getLogger(VentanaPrincipal.class.getName());
    ControlNavegacion control;
    

    public VentanaPrincipal(IInsercionMasivaBO insercionMasivaBO, ControlNavegacion control) {
        initComponents();
        this.insercionMasivaBO = insercionMasivaBO;
        this.control = control;
        setLocationRelativeTo(null);
    }
    
    private void agregarArtistasMasivamente(){
        try {
            insercionMasivaBO.insertarArtistasMasivamente();
        } catch (NegocioException ex) {
            LOG.severe("No se pudieron agregar los artistas: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al agregar artistas: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void mostrarPerfilUsuario() {
        PanelPerfilUsuario panelUsuario = new PanelPerfilUsuario(control, this);
        jPanelForms.add(panelUsuario, "perfil");
        CardLayout cl = (CardLayout) jPanelForms.getLayout();
        cl.show(jPanelForms, "perfil");
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIcono = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonAgregarArtistas = new javax.swing.JButton();
        jPanelForms = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonPerfil.png"))); // NOI18N
        jButtonIcono.setContentAreaFilled(false);
        jButtonIcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIconoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 40, 40));

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonHome.png"))); // NOI18N
        jButtonHome.setBorder(null);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButtonAgregarArtistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAgregar.png"))); // NOI18N
        jButtonAgregarArtistas.setBorder(null);
        jButtonAgregarArtistas.setContentAreaFilled(false);
        jButtonAgregarArtistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregarArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarArtistasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, -1));

        jPanelForms.setOpaque(false);
        jPanelForms.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanelForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 92, 1020, 763));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVentanaPrincipal.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonAgregarArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarArtistasActionPerformed
        agregarArtistasMasivamente();
    }//GEN-LAST:event_jButtonAgregarArtistasActionPerformed

    private void jButtonIconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIconoActionPerformed
        mostrarPerfilUsuario();
    }//GEN-LAST:event_jButtonIconoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarArtistas;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonIcono;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanelForms;
    // End of variables declaration//GEN-END:variables
}
