/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion.buscadores;

import javax.swing.event.DocumentListener;
import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author Dana Chavez
 */
    public class BuscadorCanciones extends javax.swing.JPanel {
        
    FontManager fontManager = new FontManager();
    private BusquedaListener busquedaListener;
    
    public BuscadorCanciones() {
        initComponents();
        initListeners();
        setOpaque(false);
    }
    
    private void initListeners() {
        buscadorCancion.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                notificarCambio();            
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                notificarCambio();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                notificarCambio();
            }
            
            private void notificarCambio() {
                if (busquedaListener != null) {
                    String texto = buscadorCancion.getText().trim();
                    busquedaListener.onBusquedaActualizada(texto);
                }
            }

        });
    }

    public void setBusquedaListener(BusquedaListener listener) {
        this.busquedaListener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscadorCancion = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscadorCancion.setBackground(new java.awt.Color(5, 54, 46));
        buscadorCancion.setFont(fontManager.getAfacadRegular(16f));
        buscadorCancion.setForeground(new java.awt.Color(255, 255, 255));
        buscadorCancion.setText("Nombre");
        buscadorCancion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buscadorCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorCancionActionPerformed(evt);
            }
        });
        add(buscadorCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorCancionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscadorCancion;
    // End of variables declaration//GEN-END:variables
}
