/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tune.sistemabibliotecapresentacion.buscadores;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import tune.sistemabibliotecapresentacion.utils.FontManager;

/**
 *
 * @author Dana Chavez
 */
    public class BuscadorAlbumes extends javax.swing.JPanel {
        
    FontManager fontManager = new FontManager();
    private BusquedaAlbumListener busquedaAlbumListener;
    
    public BuscadorAlbumes() {
        initComponents();
        initComboBox();
        initListeners();
    }
    
    public void initComboBox(){
        filtroBusquedaAlbums.removeAllItems();
        filtroBusquedaAlbums.addItem("Nombre");
        filtroBusquedaAlbums.addItem("Genero");
        filtroBusquedaAlbums.addItem("Fecha Lanzamiento");
    }
    
    private void initListeners() {
        buscadorAlbums.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                notificarCambio();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                notificarCambio();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                notificarCambio();
            }

            private void notificarCambio() {
                if (busquedaAlbumListener != null) {
                    String texto = buscadorAlbums.getText().trim();
                    String filtro = filtroBusquedaAlbums.getSelectedItem().toString();
                    busquedaAlbumListener.onBusquedaAlbumActualizada(texto, filtro);
                }
            }
        });

        filtroBusquedaAlbums.addActionListener(e -> {
            if (busquedaAlbumListener != null) {
                String texto = buscadorAlbums.getText().trim();
                String filtro = (String) filtroBusquedaAlbums.getSelectedItem();
                busquedaAlbumListener.onBusquedaAlbumActualizada(texto, filtro);
            }
        });
    }

    public void setBusquedaAlbumListener(BusquedaAlbumListener listener) {
        this.busquedaAlbumListener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscadorAlbums = new javax.swing.JTextField();
        filtroBusquedaAlbums = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscadorAlbums.setBackground(new java.awt.Color(5, 54, 46));
        buscadorAlbums.setFont(fontManager.getAfacadRegular(16f));
        buscadorAlbums.setForeground(new java.awt.Color(255, 255, 255));
        buscadorAlbums.setText("Nombre, genero, fecha lanzamiento");
        buscadorAlbums.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buscadorAlbums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorAlbumsActionPerformed(evt);
            }
        });
        add(buscadorAlbums, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 410, 50));

        filtroBusquedaAlbums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(filtroBusquedaAlbums, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorAlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorAlbumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorAlbumsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscadorAlbums;
    private javax.swing.JComboBox<String> filtroBusquedaAlbums;
    // End of variables declaration//GEN-END:variables
}
